### ISSUE TITLE
Hyperloop::AccessViolation on lap28 with Rails 5.2

### ISSUE THREAD

**Issue by psmir** [ruby-hyperloop/hyper-model#13]
The following code in the render method gives me such an error: `Hyperloop::AccessViolation`
```
p = Post.first
H3{ p.title } if p.present?
```
This error occures when I try to iterate over posts either:

```
Post.all.each do |p|
   H3{ p.title }
end
```

**Comment by catmando** [comment]
In order to prevent unauthorized access to information like scope counts, lists of record ids, etc, Hyperloop now (see issue https://github.com/ruby-hyperloop/hyper-mesh/issues/43) requires you explicitly allow scopes to be viewed on the client, otherwise you will get an AccessViolation.

To globally allow access to all scopes add this to the ApplicationRecord class

```ruby
class ApplicationRecord < ActiveRecord::Base
  regulate_scope :all
end
```

**Comment by catmando** [comment]
@fzingg @barriehadfield I assigned this to you, just as a reminder that we have to document the entire scope regulation system.

**Comment by psmir** [comment]
@catmando thank you

**Comment by barriehadfield** [comment]
website and gem docs updated
